# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 14:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('rate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('cost', models.CharField(max_length=10, null=True)),
                ('advance_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_des', to='utility.AdvanceDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=20, null=True)),
                ('destination_airport', models.CharField(max_length=20, null=True)),
                ('departure_date', models.DateField()),
                ('destination_date', models.DateField()),
                ('trips', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.CharField(choices=[(b'0', 0), (b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30)], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_town', models.CharField(max_length=20, null=True)),
                ('destination_town', models.CharField(max_length=20, null=True)),
                ('departure_date', models.DateField()),
                ('mileage', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Private', 'Private')], max_length=30)),
                ('trip_type', models.CharField(choices=[('One Way', 'One Way'), ('Return Flight', 'Return Flight'), ('Multiple Flight', 'Multiple Flight'), ('Road Trip', 'Road Trip')], max_length=30)),
                ('accommodation_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Lieu', 'Lieu')], max_length=20)),
                ('center_code', models.CharField(help_text='Cost Center code to be charged', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Function')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_travel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel'),
        ),
        migrations.AddField(
            model_name='meal',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel'),
        ),
        migrations.AddField(
            model_name='flight',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel'),
        ),
    ]
