# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='travel_zone',
            field=models.CharField(choices=[('Zone A', 'Zone A'), ('Zone B', 'Zone B'), ('Zone C', 'Zone C')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
