# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_zone'),
        ('flight', '0002_accommodation_travel_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.Band'),
            preserve_default=False,
        ),
    ]
