# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_travel_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
