# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20170323_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='travel_zone',
        ),
        migrations.AddField(
            model_name='travel',
            name='zone',
            field=models.CharField(choices=[('Zone A', 'Zone A'), ('Zone B', 'Zone B'), ('Zone C', 'Zone C')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
