# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20170323_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_type',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=30),
        ),
    ]
