# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_auto_20170324_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='advance_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='center_code',
            field=models.CharField(help_text='Cost Center code to be charged', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='zone',
            field=models.CharField(choices=[('Zone A', 'Zone A'), ('Zone B', 'Zone B'), ('Zone C', 'Zone C')], max_length=15, null=True),
        ),
    ]
