# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_auto_20170328_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='trips',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_cost',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
