# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20170328_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
