# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_auto_20170406_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
