# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_approvalmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
