# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_auto_20170409_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmapping',
            name='budget_team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='cco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='functional_head',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='hrd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='line_manager',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='payable_account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='travel_desk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
