# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_auto_20170409_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
