# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0019_auto_20170409_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('NAIRA', 'NAIRA')], max_length=10, null=True),
        ),
    ]
