# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0020_advance_currency'),
        ('flight', '0019_auto_20170409_2206'),
    ]

    operations = [
    ]
