# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0021_merge_20170410_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmapping',
            name='budget_team',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='cco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='functional_head',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='hrd',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='line_manager',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='payable_account',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='travel_desk',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
