# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0022_auto_20170410_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmapping',
            name='talent_team',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='employee',
            field=models.CharField(max_length=10),
        ),
    ]
