# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0023_auto_20170410_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='trip_type',
            field=models.CharField(choices=[('One Way Flight', 'One Way Flight'), ('Return Flight', 'Return Flight'), ('Multiple Flight', 'Multiple Flight'), ('Road Trip', 'Road Trip')], max_length=30),
        ),
        migrations.AlterField(
            model_name='travel',
            name='zone',
            field=models.CharField(choices=[('Zone A', 'Zone A'), ('Zone B', 'Zone B'), ('Zone C', 'Zone C')], max_length=15, null=True, verbose_name='Travel Zone'),
        ),
    ]
