# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0024_auto_20170420_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmapping',
            name='ceo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
