# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0025_approvalmapping_ceo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='advance_total',
            new_name='advance_total_dollar',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='estimated_cost',
            new_name='advance_total_naira',
        ),
        migrations.AddField(
            model_name='travel',
            name='estimated_cost_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='estimated_cost_naira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='budget_team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='cco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='ceo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='functional_head',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='hrd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='line_manager',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='payable_account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='talent_team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvalmapping',
            name='travel_desk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
