# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0026_auto_20170427_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
