# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0027_auto_20170508_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=20, null=True)),
                ('destination_airport', models.CharField(max_length=20, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('destination_date', models.DateField(blank=True, null=True)),
                ('mileage', models.CharField(max_length=11, null=True)),
                ('flight_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_return', models.BooleanField(default=False)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='road',
            name='travel',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
