# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0029_auto_20170607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='ticket_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
