# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0032_auto_20170610_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
