# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0034_auto_20170610_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='accmomodation_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
