# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0035_travel_accmomodation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='accmomodation_days',
        ),
    ]
