# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0036_remove_travel_accmomodation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='total_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='total_naira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
