# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0038_travel_cost_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150, null=True)),
                ('hotel_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel')),
            ],
        ),
    ]
