# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 21:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0040_travel_is_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], max_length=10, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('approval_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel')),
            ],
        ),
    ]
