# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0042_auto_20170920_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='approval_person_email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='approval_person_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
