# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0043_auto_20170921_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='reference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
