# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0046_auto_20170922_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='approval_person_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
