# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0048_auto_20170922_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_approval', to='flight.Travel'),
        ),
    ]
