# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0050_travel_f_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_airport',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_airport',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
