# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0051_auto_20171204_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
