# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0052_travel_is_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='team_len',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
