# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0053_travel_team_len'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auuid', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Travel')),
            ],
        ),
    ]
