# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0054_teamtravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtravel',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='teamtravel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamtravel',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamtravel', to='flight.Travel'),
        ),
    ]
