# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0055_auto_20180511_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=20, null=True),
        ),
    ]
