# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_name', models.CharField(help_text='Campaign Name', max_length=30)),
                ('broadcast_description', models.CharField(blank=True, help_text='Campaign Description', max_length=150, null=True)),
                ('content_type', models.CharField(choices=[('Text', 'Text'), ('Flash', 'Flash')], max_length=12)),
                ('sender', models.CharField(help_text='Sender', max_length=30)),
                ('message', models.TextField()),
                ('schedule_start', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('sms_upload_path', models.CharField(blank=True, help_text='Please upload file', max_length=150, null=True)),
                ('recipient_count', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Text', 'Text'), ('Flash', 'Flash')], max_length=12)),
                ('message', models.TextField()),
                ('schedule_start', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('name_id', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='broadcast',
            name='base_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Uploads'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_broad', to='account.UserProfile'),
        ),
    ]
