# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_upload', to='account.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='content_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], max_length=12),
        ),
        migrations.AlterField(
            model_name='push',
            name='content_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], max_length=12),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
