# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20190405_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='name_id',
            field=models.CharField(max_length=50),
        ),
    ]
