# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20190405_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_broad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
