# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20190405_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='recipient_count',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
