"""
Django settings for AirtelTravel project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
#import djcelery

#djcelery.setup_loader()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sr9cp=z!1na=pv89zld3#d#!2_#6gk4q$e&!x_3zg*1+d+4xm*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

IN_ZONE_FLOW=('')

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/login'
# Application definition


# LDAP = 'http://172.24.91.109:7777/Auth/Validate?'
# GET_EMAIL = 'http://172.24.91.109:7777/Auth/GetStaffDetails?'
# USERNAME = '2330854'
# PASSWORD = 'Eforir0#01'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    #'flight',
    'campaign',
    'webpack_loader'
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'account.middleware.DelegateMiddleware',
    #'django_session_timeout.middleware.SessionTimeoutMiddleware'
]

ROOT_URLCONF = 'newunica.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [ BASE_DIR,
                  os.path.join(BASE_DIR, 'newunica/templates'),
                  os.path.join(BASE_DIR, 'account/templates').replace('\\', '/'),
                  os.path.join(BASE_DIR, 'campaign/templates').replace('\\', '/'),],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newunica.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'emails')

SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 3600 

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
#
# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
# }

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'UNICA',
         'USER': 'root',
         'PASSWORD': '',
         'HOST': '127.0.0.1',
         'PORT': '3306',
     }
 }

username='test'
password='test123'

#SMS
SEND_SMS_URL = "http://172.24.103:15498/cgi-bin/sendsms?"
REDIS_SERVER = "172.24.6.103"
REDIS_PASS = "8aB4wnwfn7Fj?ZB"
KEY = "CDR_CARD"

CELERY_BROKER_URL = 'amqp://cwc:london@172.24.6.103:5672'

#SITE_URL = '172.24.91.37:8645'
SITE_URL = 'http://127.0.0.1:8000/'

#SITE_URL = 'https://travelportal.ng.airtel.com/'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REDIS_SERVER = '172.24.2.68'
#REDIS_SERVER = '172.24.11.91:8800'
APPROVAL_KEY = 'TRAVEL_REQUEST'

ALLOWED_TYPE = ['plain', 'plain', 'csv', 'txt']
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# SEND_EMAIL = 'http://172.24.91.109:3030/api/email'
# QUERY_USERNAME = '2330854'
# QUERY_PASSWORD = 'Oct08@2018'
#
# LDAP_URL = 'http://172.24.11.84:8888/auth/getstaffdetails?'
# DELEGATE_URL = 'http://172.24.2.123:5105/CRFAutomation/getdelegate?'
# SET_DELEGATE = 'http://172.24.2.123:5105/CRFAutomation/updateleaveapi'
# DEACTIVATE = 'http://172.24.2.123:5105/CRFAutomation/cancelleave?'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = (os.path.join(BASE_DIR, 'static'))

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': '',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': ['.+\.hot-update.js', '.+\.map']
    }
}

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(BASE_DIR, '/static'),
    os.path.join(os.path.dirname(__file__), 'static'),
    os.path.join(BASE_DIR, 'newunica/dist')
)

FILTERED_BACTHES_FILE_LOCATION = os.path.join(PROJECT_PATH, 'filteration_batches')
MEDIA_ROOT = os.path.join(os.path.dirname(__file__), 'upload')
MEDIA_URL = '/upload/'

TRAVEL_POLICY=os.path.join(os.path.dirname(__file__), 'policy')

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

